# Generated by Django 5.2.4 on 2026-04-29 23:16

import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="voter_id",
            field=models.CharField(
                default=voting.models.generate_voter_id, max_length=100, unique=True
            ),
        ),
    ]
