# Generated by Django 5.2.4 on 2026-05-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0002_alter_voter_voter_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voter",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voter",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="International format, e.g. +2348100000000",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
