# Generated by Django 5.2.4 on 2026-05-01 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0003_voter_email_voter_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Superadmin who created this admin account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="is_admin",
            field=models.BooleanField(
                default=False, help_text="Can manage election operations"
            ),
        ),
        migrations.AddField(
            model_name="voter",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Force password change on next login (set by superadmin)",
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("LOGIN_FAILED", "Failed Login Attempt"),
                            ("PASSWORD_CHANGE", "Password Changed"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("VOTE_CAST", "Vote Cast"),
                            ("VOTES_RESET", "All Votes Reset"),
                            ("ADMIN_CREATED", "Admin Account Created"),
                            ("VOTER_CREATED", "Voter Registered"),
                            ("VOTER_DELETED", "Voter Deleted"),
                            ("CATEGORY_CREATED", "Category Created"),
                            ("CATEGORY_UPDATED", "Category Updated"),
                            ("CATEGORY_DELETED", "Category Deleted"),
                            ("NOMINEE_CREATED", "Nominee Added"),
                            ("NOMINEE_DELETED", "Nominee Deleted"),
                            ("PHONE_VERIFIED", "Phone Verified"),
                            ("EMAIL_VERIFIED", "Email Verified"),
                            ("ACCESS_CODE_USED", "Access Code Used"),
                            ("SYSTEM_UPDATE", "System Update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "target_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("target_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "target_repr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed this action (null = anonymous/system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
