# Generated by Django 5.2.4 on 2026-05-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "voting",
            "0004_vote_city_vote_country_vote_ip_address_vote_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="admin_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("voter_manager", "Voter Manager"),
                    ("nominee_manager", "Nominee Manager"),
                    ("results_viewer", "Results Viewer"),
                    ("full_admin", "Full Admin"),
                ],
                help_text="Specific permission set assigned by superadmin",
                max_length=30,
                null=True,
            ),
        ),
    ]
